### ISSUE TITLE
Grid - Layout (Vertical Gutter Value)

### ISSUE THREAD

**Issue by SinaTaavon** [twilio-labs/paste#1673]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
On the ```grid``` layout system, there is a ```gutter``` option which gives space on the X-Axis but when the ```grid``` is set to ```vertical``` the gutter still applies to the X-Axis, that might be by design but if we could have a ```vGutter``` prop so we can set space on top and bottom of the ```columns```, Alternatively ```gutter``` could apply the space to both axis.

Note: Manual margin gets ignored if ```grid``` is in use rather than ```flex```. That's why having a prop for the vertical gutter would be really helpful.

**To Reproduce**
The issue is visible on the Storybook for paste and no need to reproduce it.

Link to the Storybook's component where the issue is visible (You can change the window size to change it to vertical) https://5e53448165911c0022e68c74-erijdslbuz.chromatic.com/?path=/docs/layout-grid--grid-12-column-and-gutter-support#grid---equal-height-columns

**Expected behaviour**
A prop to pass the vertical value for the ```gutter```. like ```vGutter``` or something similar.
Alternatively ```gutter``` to apply the space to both axis.

**Screenshots**
![image](https://user-images.githubusercontent.com/32191839/125795749-18611be8-4590-4a4f-9d2a-2efaad451354.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS 
 - Browser [e.g. chrome, safari] Opera, Chrome, Safari
 - Version [e.g. 22] Opera: 77, Chrome: 91.0.4472.124, Safari: 14.1 

**Additional context**
Overall Paste is looking very Strong candidate to replace Bootstrap and Material UI, for a Beta product I can confidently say that is extremely polished, just a couple of small changes and it will be one of the best frameworks that we have used to this day. 

Thanks for your time.

**Comment by andipants12** [comment]
Hi @SinaTaavon,

Thank you for the bug report and the suggested addition to the `Grid` API. We are discussing solutions as a team and will get back to you early next week with some updates on how we plan to move forward. 

Thank you for raising this issue, the encouraging words, and helping us improve Paste. 🎉

**Comment by andipants12** [comment]
Hello again @SinaTaavon 👋, we have a pull request open now to resolve this issue, which is linked above.

For now we opted to simply apply the gutter spacing value to either the top/bottom or right/left boundaries accordingly. We took this path rather than add additional properties to the component API as we have plans to release a new `Grid` component that is built on CSS grids in the future.

Please let us know if you have any more questions and feel free to leave some feedback on the changes.
Thank you again for helping us make Paste better and being a member of our community. 🥇

**Comment by SinaTaavon** [comment]
Hey, @andipants12 That's amazing, I am following the pull request information on GitHub, I won't be getting notifications but I will check it here and then just to see what's new. 

Thanks again for the info 😃

**Comment by andipants12** [comment]
Hey there, @SinaTaavon!

Wanted to circle back and let you know that the fix is available starting with `@twilio-paste/grid@2.1.0`. 🚀
We have also updated the [Grid component documentation](https://paste.twilio.design/layout/grid/#responsive-columns) with a few more examples of responsive columns and usage with the vertical prop.

I'll close this issue for now, but please reopen if you feel this does not address your original concern.

Thank you again for your feedback and help to improve Paste! 🌟
