### ISSUE TITLE
Button value prop not passed to the onClick handler event

### ISSUE THREAD

**Issue by george-cz** [twilio-labs/paste#2422]
Thanks for helping make Paste better! For general questions or feature requests, please post [a discussion](https://github.com/twilio-labs/paste/discussions/new).

**Describe the bug**
When a `value` prop is passed to a Button, the value cannot be read from the `event.target` in the `onClick` handler, because the `event.target` is actually a `span` element inside the button, which doesn't have a `value` prop.

The `value` prop is useful in case we are rendering a table and have a button with a specific id on each row.

The workaround right now is to not memoize the callback:

`<Button onClick={() => doSomething(item.id)}>`, but ideally we'd want to be able to pass a value and a memoized handler instead.

**To Reproduce**

1. Go to https://codesandbox.io/s/paste-starter-kit-forked-c6o7be?file=/src/index.tsx
2. Click on the button
4. See `undefined` instead of SID123

**Expected behavior**
The onClick handler should be able to access the `value` prop of the Button under the `event.target.value`

**Screenshots**
N/A, see codesandbox

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome 100
- Version 13.0.0

**Comment by nkrantz** [comment]
Hey @george-cz, sorry for the delay. Checking this out now and will update this thread soon.

**Comment by nkrantz** [comment]
Hi again @george-cz - just got caught up on this Issue. It doesn't strike me as a bug, because we intentionally place a `span` inside of our Button component for various reasons. Rather than using the Button `value` to determine which Button was clicked, a better approach would be to use unique click handlers for each Button. You could either have unique functions for each click handler, or pass in a unique identifier to the click handler, like so: `<Button onClick{() => doSomething("firstButton")}>`. That way, you also won't have as much code to update if the Button text ever changes.

If you're still in need of a way to access the Button text from the handler, you can use either `event.target.innerText` or `event.target.childNodes[0].wholeText` to get that `value`.

**Comment by george-cz** [comment]
**I believe it is a bug since it works if you click the edge of the button and not the text. T**he span inside is an implementation detail and the developer shouldn't be too concerned about it, however its breaking the functionality here. 

I've also updated the sandbox to contain default HTML button to see how it should work

**Comment by george-cz** [comment]
This is clearly a bug and was closed as complete with a workaround provided, are we really ok with this being broken?

**Comment by SiTaggart** [comment]
Hi @george-cz 

It's difficult to call it a bug I'm afraid as it's just the default browser behaviour of click handlers. 

This kind of behaviour can even be seen with Material UI in this codesandbox example I whipped up for you. https://codesandbox.io/s/paste-starter-kit-forked-nxj9nj?file=/src/index.tsx

If you click on the send icon in the MUI button example, you will always get undefined when using `evenet.target.value`. Click next to it, you'll click the button element and it'll work. Where-as using `event.currentTarget` will always return what you're after, regardless of the HTML structure inside the button and where you click inside of it.

It's always a risk with using `event.target`
