### ISSUE TITLE
whiteSpace property of Text component is not applied.

### ISSUE THREAD

**Issue by ashinde-git** [twilio-labs/paste#2521]
Thanks for helping make Paste better! For general questions or feature requests, please post [a discussion](https://github.com/twilio-labs/paste/discussions/new).

**Describe the bug**
When you add the `whiteSpace` property to a Text component, it is not present in the css class.
Other properties are correctly applied and are present in the css.

**To Reproduce**

1. Add a text component to your react code.
2. Use the 'whiteSpace' property and set the value to any of the possible `ResponsiveValue<WhiteSpaceOptions>` like '`pre-line`', '`pre-wrap`', '`break-spaces`'.
3. Check the css class that is generated for this text component. The property isn't applied.

**Expected behavior**
Text component should use the whitespace property.

**Screenshots**
![Screen Shot 2022-07-08 at 3 18 54 PM](https://user-images.githubusercontent.com/106102933/178077441-27054e31-f922-48cb-b799-6a19df7f2a49.png)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Mac OS
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] "@twilio-paste/text" "3.0.0" , "@twilio-paste/core": "^6.0.1",

**Comment by shleewhite** [comment]
Hi @ashinde-git!

It seems like you are using an older version of Paste and the Text component. This bug was fixed in `@twilio-paste/text@4.1.4` ([changelog](https://paste.twilio.design/primitives/text#4-1-4)). If you update to the latest version of `@twilio-paste/core`, it should work as expected: https://codesandbox.io/s/text-whitespace-example-ezfz1v.

Please let me know if you have any more questions!

**Comment by ashinde-git** [comment]
@shleewhite Awesome. Will update the version. Thank you for the help.
