### ISSUE TITLE
Require <Checkbox> missing label indicating "(required)"

### ISSUE THREAD

**Issue by patcon** [twilio-labs/paste#2567]
**Describe the bug**
In the internationalization section for `<CheckboxGroup>` component, there's  nifty prop `i18nRequiredLabel` to set the non-english hidden label for visual "required" dot, for which that text shows up in the markup. When it's not included, "(required)" shows in the markup.
https://paste.twilio.design/components/checkbox/#internationalization

But for the checkboxes component `<Checkbox>` with the `required` prop, there is no hidden text for screen readers, just an empty span in markup:
https://paste.twilio.design/components/checkbox/#required-checkbox

**To Reproduce**
Steps to reproduce the behaviour:

1. View markup in the two examples above.

**Expected behavior**
Would expect "(required)" to show up in `<Checkbox required>` components as it does in `<CheckboxGroup required>`, as text that's hidden visually, but shows in markup and for screen-readers. Further, if there is a prop set on `<Checkbox required i18nRequiredLabel="(requis)">`, I would expect that to replace the english.

**Screenshots**
<img width="598" alt="Screen Shot 2022-07-28 at 3 37 49 PM" src="https://user-images.githubusercontent.com/305339/181623031-9396d483-108a-4099-a926-8f972b2fa403.png">

**Desktop (please complete the following information):**

- OS: OSX 11.6.5 (20G527)
- Browser Chrome
- Version Version 103.0.5060.134 (Official Build) (x86_64)

**Additional context**
Work-around might be to add english text manually via `<Checkbox required i18nRequiredLabel="(required)" />`

**Comment by shleewhite** [comment]
Hi @patcon!

This is actually working as expected, but we definitely could document it better.

All inputs in HTML have [a required attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required) which is announced by screen readers.

The CheckboxGroup is an HTML fieldset under the hood. Unlike inputs, there isn't a global way to indicate that you are required to select something from the group. To get around this, we add the visually hidden text "(required)" so that screen reader users know.

For inputs, it is safe to rely on the native HTML attribute so we don't need to add visually hidden text. This is better for internationalization too because the screen reader and OS can handle it for us 😄.

Please let me know if you have any other questions about this!

**Comment by patcon** [comment]
Ah, thank you! Sorry, I was looking for an input, but just didn't look above, so missed what was happening :)
