### ISSUE TITLE
Whitney font unaccessible

### ISSUE THREAD

**Issue by GiantRobots** [twilio-labs/paste#258]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

## Is this related to an existing Paste Component? Please link it here:

The Whitney font is unaccessible to developers so they can host it in their own application.

**Comment by SiTaggart** [comment]
Whitney is only available to certain domains. It's OK to use on *.twilio.com domain and localhost. 

Because Whitney users are for Twilio console only, console automatically loads the whitney fonts you need from the type foundry CDN for you. 

We do need to better document that pre-requisite though.

**Comment by TheSisb** [comment]
Resolved by https://github.com/twilio-labs/paste/pull/259
