### ISSUE TITLE
Controlled Combobox caret jumping to end when trying to update a previous part of the text 

### ISSUE THREAD

**Issue by mannycolon** [twilio-labs/paste#2618]
Thanks for helping make Paste better! For general questions or feature requests, please post [a discussion](https://github.com/twilio-labs/paste/discussions/new).

**Describe the bug**
When typing a help request query, and trying to update a previous part of the text, the caret jumps to the end after the first keystroke. This negatively impacts UX and makes text editing difficult. 

**To Reproduce**

1. Go to [Controlled Combobox](https://paste.twilio.design/components/combobox/#controlled-combobox).
2. Click on the combobox and type any text.
3. Click on the beginning of the text and type 123, see how the caret jumps to the end of input box.

**Expected behavior**
Caret should not jump to the end of the input box when updating a Combobox value. 

**Screenshots**
![image](https://user-images.githubusercontent.com/17072300/185493682-6026430b-092b-4468-8e62-9a2c33806800.png)

Desktop (please complete the following information):

OS: macOS
Browser: Chrome
Version 104.0.5112.79

**Comment by shleewhite** [comment]
Hi @mannycolon!

Thank you for posting this, we are investigating the issue now.

**Comment by SiTaggart** [comment]
Hi @mannycolon 

There is a small fix incoming in this PR #2647, along with some doc example updates.

If you are using the `useCombobox` hood from Combobox, you don't need to wait for the fix to merge. We had a bad example. When doing controlled comboboxes and the hook, rather than setting `inputValue`, allow Downshift to control the state internally. Just switch `inputValue` to setting `initialInputValue`, and keep everything else. This fixes the cursor jumping.

If you are not using the hook, then you'll have to wait for that PR to merge and we'll come back to let you know if was released.

**Comment by mannycolon** [comment]
Hi @SiTaggart,

Awesome, thank you so much. I've already fix the problem on our implementation by following along your PR changes. We are using the useCombobox hook and it was as easy as just updating the variable names as you said. Thank you so much for your help.

Regards!

**Comment by SiTaggart** [comment]
This is now released in Paste Core v15.2
