### ISSUE TITLE
Tooltip keeps showing up even if I don't hover over the icon

### ISSUE THREAD

**Issue by gsiradze** [twilio-labs/paste#3733]
### Description

The tooltip keeps showing after closing a modal. It needs an additional click to disappear it

https://github.com/twilio-labs/paste/assets/6205690/28020fdf-facf-448c-8cea-56317afe0963

### Link to Reproduction

https://codesandbox.io/p/sandbox/customizing-components-forked-qwrghs

### Paste Core Version

20.7.0

### Browser

Google Chrome 120

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by SiTaggart** [comment]
Hi there

This is expected behavior for your interaction.

When creating accessible experiences, tracking and maintaining focus of the user cursor is required. So when you trigger a transient UI element from a trigger, we place the users focus into the newly rendered UI element. Upon dismissing it, you must return the user back to the triggering element so they can maintain context and their location in the application. This is vital for users that don't use a mouse.

So when the focus is return the triggering button, the tooltip will show, because the button is focused.
