### ISSUE TITLE
Twilio Bootstrap transforming text to upper case.

### ISSUE THREAD

**Issue by andipants12** [twilio-labs/paste#497]
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
`bootstrap.css` is transforming the text for `<FormLabel />` and `<Radio />` to upper case.

**To Reproduce** 
The feature I am working on is not released in prod. (this section will be updated by Jiexi later)

**Expected behavior**
Text for labels, and options should not be transformed to upper case.

**Screenshots**
`<FormLabel />` transformed:
<img width="821" alt="Screen Shot 2020-06-10 at 4 24 55 PM" src="https://user-images.githubusercontent.com/18120906/84328498-fa0d9800-ab36-11ea-966e-3f6a7e9ca9e9.png">

`<Radio />` descriptive text transformed:
<img width="785" alt="Screen Shot 2020-06-10 at 4 24 41 PM" src="https://user-images.githubusercontent.com/18120906/84328512-04c82d00-ab37-11ea-8306-19cbf405db53.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome

**Additional context**
n/a

**Comment by ghostling** [comment]
Can't edit the original post since it's not mine, but here's the bootstrap rule that is overriding these styles:
<img width="260" alt="LabelStyles" src="https://user-images.githubusercontent.com/2553665/84328730-9d5ead00-ab37-11ea-91ab-dba96dc138bd.png">

Also noticed that for `<RadioGroup />`, there's a horizontal line under the legend that is not present in the Paste component. This is coming from:
<img width="259" alt="LegendStyles" src="https://user-images.githubusercontent.com/2553665/84328827-f0386480-ab37-11ea-833e-6eb0a87b10fa.png">

---

Here's another example of these two elements:

Inside Console:
<img width="454" alt="InConsole" src="https://user-images.githubusercontent.com/2553665/84328858-03e3cb00-ab38-11ea-9bf3-cca25ee87ec7.png">

Outside Console:
<img width="454" alt="OutsideConsole" src="https://user-images.githubusercontent.com/2553665/84328895-1bbb4f00-ab38-11ea-97ae-edbaf537c4af.png">

**Comment by SiTaggart** [comment]
Hi @andipants12 and @ghostling, thanks for the issue and screenshots. It's added to our backlog.

Any chance either or both of you can provide a link to a page in console that we can see these too, just in case we can spot anything else we need to be defensive against?

**Comment by ghostling** [comment]
The modal above can be found on this page: https://www.twilio.com/console/iot/supersim/network-access-profiles after clicking the blue + button on the table.

**Comment by andipants12** [comment]
@SiTaggart The page I'm working on isn't in prod yet, but I have a branch deployed in stage currently. Let me know if you'd like me to send info on access to that. Otherwise, I have signed up for a crit session next week to go over the UI. We can address then as well. Let me know what is best.

**Comment by SiTaggart** [comment]
@andipants12 yeah if you can DM me the stage URLs in Slack, that would be amazing

**Comment by andipants12** [comment]
@SiTaggart sorry about that, I just saw this. I don't get email notifications for Github anymore. I will send it to you in the morning.

**Comment by margusha** [comment]
confirming the same issue, bootstrap overrides text labels to uppercase.

**Comment by TheSisb** [comment]
Merged in a fix, please re-open issue if not resolved after updating Paste deps. <3

**Comment by ghostling** [comment]
@TheSisb should the change fix the `border-bottom` on `legend` as well? I'm not seeing that changed:
<img width="1730" alt="Screen Shot 2020-07-01 at 12 09 00 PM" src="https://user-images.githubusercontent.com/2553665/86282232-b33e1b80-bb93-11ea-8b4d-691baa871838.png">

**Comment by SiTaggart** [comment]
Whoops! We may have missed that one @ghostling. We'll get it out this week.

**Comment by ghostling** [comment]
I created a new issue to track this separately: https://github.com/twilio-labs/paste/issues/556

**Comment by andipants12** [comment]
@TheSisb Fixed! Thank you so much!
